json.id task.id
json.lead_id task.lead_id
json.user_id task.user_id
json.title task.title
json.kind task.kind
json.due_at task.due_at
json.completed_at task.completed_at
json.created_at task.created_at
json.lead_name task.lead.name
